import { Category, Transaction, Budget, SavingsGoal, NotificationItem, Profile } from '../types';
import { format, subDays } from 'date-fns';

const today = new Date();
const formatDate = (daysAgo: number) => format(subDays(today, daysAgo), 'yyyy-MM-dd');

export const INITIAL_PROFILE: Profile = {
  id: 'usr_demo_01',
  full_name: 'Ismail Alabi',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  preferred_currency: 'NGN',
  low_balance_threshold: 20000,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat_food', user_id: 'usr_demo_01', name: 'Food & Groceries', type: 'expense', icon: 'Utensils', color: '#ef4444', created_at: new Date().toISOString() },
  { id: 'cat_transport', user_id: 'usr_demo_01', name: 'Transportation', type: 'expense', icon: 'Car', color: '#f97316', created_at: new Date().toISOString() },
  { id: 'cat_housing', user_id: 'usr_demo_01', name: 'Rent & Housing', type: 'expense', icon: 'Home', color: '#eab308', created_at: new Date().toISOString() },
  { id: 'cat_utilities', user_id: 'usr_demo_01', name: 'Utilities & Data', type: 'expense', icon: 'Zap', color: '#84cc16', created_at: new Date().toISOString() },
  { id: 'cat_education', user_id: 'usr_demo_01', name: 'Education & Supplies', type: 'expense', icon: 'BookOpen', color: '#06b6d4', created_at: new Date().toISOString() },
  { id: 'cat_health', user_id: 'usr_demo_01', name: 'Health & Medical', type: 'expense', icon: 'Activity', color: '#3b82f6', created_at: new Date().toISOString() },
  { id: 'cat_entertainment', user_id: 'usr_demo_01', name: 'Leisure & Outings', type: 'expense', icon: 'Film', color: '#a855f7', created_at: new Date().toISOString() },
  { id: 'cat_savings', user_id: 'usr_demo_01', name: 'Savings & Investments', type: 'expense', icon: 'PiggyBank', color: '#8b5cf6', created_at: new Date().toISOString() },
  { id: 'cat_transfers', user_id: 'usr_demo_01', name: 'Transfers & Banking', type: 'expense', icon: 'Repeat', color: '#6e44ff', created_at: new Date().toISOString() },
  { id: 'cat_salary', user_id: 'usr_demo_01', name: 'Salary & Income', type: 'income', icon: 'Briefcase', color: '#10b981', created_at: new Date().toISOString() },
  { id: 'cat_freelance', user_id: 'usr_demo_01', name: 'Side Gig / Stipend', type: 'income', icon: 'DollarSign', color: '#14b8a6', created_at: new Date().toISOString() },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx_demo_01',
    user_id: 'usr_demo_01',
    type: 'income',
    category_id: 'cat_salary',
    amount: 295263.02,
    date: formatDate(1),
    description: 'Monthly Salary Payment',
    payment_method: 'Bank Transfer',
    is_recurring: true,
    recurrence_interval: 'monthly',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'tx_demo_02',
    user_id: 'usr_demo_01',
    type: 'expense',
    category_id: 'cat_transfers',
    amount: 271760.00,
    date: formatDate(3),
    description: 'Investment Vault & Savings Deposit',
    payment_method: 'Bank Transfer',
    is_recurring: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'tx_demo_03',
    user_id: 'usr_demo_01',
    type: 'expense',
    category_id: 'cat_food',
    amount: 18500.00,
    date: formatDate(4),
    description: 'Supermarket Grocery Run',
    payment_method: 'Debit Card',
    is_recurring: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'tx_demo_04',
    user_id: 'usr_demo_01',
    type: 'expense',
    category_id: 'cat_utilities',
    amount: 7081.00,
    date: formatDate(7),
    description: 'Fiber Broadband & Power Bill',
    payment_method: 'Direct Debit',
    is_recurring: true,
    recurrence_interval: 'monthly',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'tx_demo_05',
    user_id: 'usr_demo_01',
    type: 'expense',
    category_id: 'cat_transport',
    amount: 4200.00,
    date: formatDate(9),
    description: 'Ride Share & Commute Pass',
    payment_method: 'Debit Card',
    is_recurring: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'tx_demo_06',
    user_id: 'usr_demo_01',
    type: 'income',
    category_id: 'cat_freelance',
    amount: 45000.00,
    date: formatDate(12),
    description: 'Freelance Design Milestone Payout',
    payment_method: 'Bank Transfer',
    is_recurring: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'tx_demo_07',
    user_id: 'usr_demo_01',
    type: 'expense',
    category_id: 'cat_entertainment',
    amount: 6500.00,
    date: formatDate(14),
    description: 'Cinema Outing & Dinner',
    payment_method: 'Cash',
    is_recurring: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'tx_demo_08',
    user_id: 'usr_demo_01',
    type: 'expense',
    category_id: 'cat_health',
    amount: 8500.00,
    date: formatDate(18),
    description: 'Pharmacy & Wellness Checkup',
    payment_method: 'Debit Card',
    is_recurring: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'tx_demo_09',
    user_id: 'usr_demo_01',
    type: 'expense',
    category_id: 'cat_food',
    amount: 14200.00,
    date: formatDate(21),
    description: 'Weekly Grocery Supplies',
    payment_method: 'Debit Card',
    is_recurring: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'tx_demo_10',
    user_id: 'usr_demo_01',
    type: 'expense',
    category_id: 'cat_transport',
    amount: 3800.00,
    date: formatDate(25),
    description: 'Vehicle Refueling',
    payment_method: 'Debit Card',
    is_recurring: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const INITIAL_BUDGETS: Budget[] = [
  {
    id: 'bdg_demo_01',
    user_id: 'usr_demo_01',
    title: 'Monthly Food & Groceries Cap',
    amount: 55000,
    period_type: 'monthly',
    start_date: formatDate(30),
    end_date: formatDate(-5),
    category_id: 'cat_food',
    notes: 'Keep weekly grocery runs under ₦15,000.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'bdg_demo_02',
    user_id: 'usr_demo_01',
    title: 'Transport & Commute Cap',
    amount: 20000,
    period_type: 'monthly',
    start_date: formatDate(30),
    end_date: formatDate(-5),
    category_id: 'cat_transport',
    notes: 'Optimize commute and ride shares.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'bdg_demo_03',
    user_id: 'usr_demo_01',
    title: 'Utilities & Subscriptions Limit',
    amount: 15000,
    period_type: 'monthly',
    start_date: formatDate(30),
    end_date: formatDate(-5),
    category_id: 'cat_utilities',
    notes: 'Fiber internet and electricity tokens.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const INITIAL_SAVINGS_GOALS: SavingsGoal[] = [
  {
    id: 'svg_demo_01',
    user_id: 'usr_demo_01',
    name: 'Emergency Reserve Fund',
    target_amount: 250000,
    current_amount: 135000,
    deadline: formatDate(-90),
    notes: 'Targeting 3 months of essential living expenses.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'svg_demo_02',
    user_id: 'usr_demo_01',
    name: 'Tech Upgrade Vault',
    target_amount: 180000,
    current_amount: 60000,
    deadline: formatDate(-60),
    notes: 'Saving for a high-performance workstation.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'ntf_demo_01',
    user_id: 'usr_demo_01',
    type: 'warning',
    title: 'Predictive Burn Rate Alert',
    message: 'At current daily spending, your cash runway is estimated at 11 days. Review non-essential spending caps.',
    is_read: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ntf_demo_02',
    user_id: 'usr_demo_01',
    type: 'info',
    title: 'Welcome to TrackFi',
    message: 'Your financial sustainability tracking environment has been provisioned.',
    is_read: true,
    created_at: new Date().toISOString(),
  }
];
